[package]
name = "tag-repo"
version = "0.0.0"
description = "A Tauri App"
authors = ["jamesWalker55"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.2", features = ["api-all"] }
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/tauri-plugin-window-state", rev = "17f468062904e64bb3ebf5f1b7486883aaafa1cf" }
window-shadows = { git = "https://github.com/tauri-apps/window-shadows", rev = "38e89e93340e3ecd44e6f6cdfdd810df9f7b3073" }
time = { version = "0.3.17", features = ["std"] }
rusqlite = { version = "0.28.0", features = ["bundled"] }
indoc = "2"
rusqlite_migration = "1.0.1"
lazy_static = "1.4.0"
tempfile = "3.4.0"
notify = { version = "5.1.0", default-features = false, features = ["macos_kqueue"] }
notify-debouncer-mini = "0.2.0"
futures = "0.3.26"
futures-timer = "3.0.2"
nom = "7.1.3"
itertools = "0.10.5"
tokio = { version = "1.26.0", features = ["full"] }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]

# Config for the UI main file
# If you're only working on the lib, comment out this section to stop the error when running `cargo test`
[[bin]]
name = "main"
path = "src/main_tauri.rs"

[lib]
name = "lib"
path = "src/lib.rs"
test = true
